#!/bin/sh

if [ x"$1" = x"sh" -o x"$1" = x"bash" ]; then
  exec $@
  exit
fi

[ ! -e /kibana/config/kibana.yml ] \
  && echo "Generating configs" \
  && cp -R /kibana/config.orig/* /kibana/config/

exec su kibana -c "kibana/bin/kibana $@"
